#!/usr/bin/env python3
"""Generate Claude Code-compatible configuration from Harness configuration.

Reads .harness/harness.yaml (source of truth) and writes projections under
.claude/. Does not modify canonical rules/, skills/, profiles/, tools/, or
docs/tools/. Does not manage or overwrite project CLAUDE.md.

Treats configuration and resource files as data — never eval/exec their content.

Preferred invocation (no sys.path mutation):

    python -m adapters.claude.generate --root .

Direct script execution still works via a minimal path bootstrap for local
development without packaging.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ADAPTER_DIR = Path(__file__).resolve().parent
REPO_ROOT_DEFAULT = ADAPTER_DIR.parent.parent

# Script-mode bootstrap only. Prefer: python -m adapters.claude.generate
if __package__ is None:  # pragma: no cover - exercised via CLI subprocess
    repo_root = str(REPO_ROOT_DEFAULT)
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)

from adapters.common.apply import (  # noqa: E402
    PlannedFile,
    apply_preflighted_plan,
    load_manifest,
    preflight,
)
from adapters.common.frontmatter import parse_skill_frontmatter  # noqa: E402
from adapters.common.metadata import (  # noqa: E402
    AdapterMetadata,
    AdapterMetadataError,
    assert_plan_matches_capabilities,
    load_adapter_metadata,
)
from adapters.common.resolve import (  # noqa: E402
    MANAGED_MARKER,
    ResolutionError,
    ResolvedHarness,
    resolve_harness,
)


def posix_rel(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def rule_projection_content(canonical_rel: str, category: str, stem: str, body: str) -> str:
    """Materialize a Claude project rule under .claude/rules/.

    Official Claude Code docs: rules are ``.md`` files under ``.claude/rules/``,
    discovered recursively. Rules without ``paths`` frontmatter load at launch.

    ``@path`` imports are documented for CLAUDE.md files, not for
    ``.claude/rules/``. This adapter therefore embeds the canonical Rule body
    (regenerate to sync) rather than inventing an unverified import mechanism.
    """
    normalized = body.replace("\r\n", "\n").replace("\r", "\n")
    if not normalized.endswith("\n"):
        normalized += "\n"
    return (
        f"{MANAGED_MARKER}\n\n"
        f"# Harness Rule: {category}/{stem}\n\n"
        "This file is a Claude Code projection generated by the AI Engineering "
        "Harness.\n\n"
        f"Canonical Rule (source of truth): `{canonical_rel}`\n\n"
        "Do not edit this file by hand. Change the canonical Rule and regenerate.\n\n"
        "---\n\n"
        f"{normalized}"
    )


def skill_wrapper_content(skill_id: str, description: str, canonical_rel: str) -> str:
    """Thin Claude skill wrapper under .claude/skills/<skill-id>/SKILL.md.

    Official Claude Code docs: skills live at ``.claude/skills/<name>/SKILL.md``
    with YAML frontmatter ``name`` / ``description`` and a markdown body.
    There is no verified remote-skill path that points outside discovery roots,
    so the wrapper preserves frontmatter and instructs the agent to follow the
    canonical Skill file.
    """
    safe_description = description.replace('"', "'")
    return (
        "---\n"
        f"name: {skill_id}\n"
        f'description: "{safe_description}"\n'
        "---\n\n"
        f"{MANAGED_MARKER}\n\n"
        f"# {skill_id}\n\n"
        "This file is a Claude Code projection generated by the AI Engineering Harness.\n\n"
        "Canonical Skill (source of truth):\n\n"
        f"`{canonical_rel}`\n\n"
        "When this skill applies, read that file and follow its workflow. "
        "Do not invent steps that are not in the canonical Skill.\n"
    )


def build_plan(
    resolved: ResolvedHarness,
    metadata: AdapterMetadata,
) -> tuple[list[PlannedFile], list[str]]:
    planned: list[PlannedFile] = []
    warnings: list[str] = []

    rules_dir = metadata.output_path("rules_dir").rstrip("/")
    skills_dir = metadata.output_path("skills_dir").rstrip("/")

    if resolved.rule_files and not metadata.supports("rules"):
        raise AdapterMetadataError(
            "Resolved Rules are selected but adapter.yaml does not support 'rules'"
        )
    if resolved.skill_files and not metadata.supports("skills"):
        raise AdapterMetadataError(
            "Resolved Skills are selected but adapter.yaml does not support 'skills'"
        )

    if metadata.supports("rules"):
        for rule_path in resolved.rule_files:
            rel = posix_rel(rule_path, resolved.root)
            category = rule_path.parent.name
            stem = rule_path.stem
            out_rel = f"{rules_dir}/{category}--{stem}.md"
            body = rule_path.read_text(encoding="utf-8")
            planned.append(
                PlannedFile(
                    relative_path=out_rel,
                    content=rule_projection_content(rel, category, stem, body),
                    kind="rule",
                )
            )

    if metadata.supports("skills"):
        for skill_path in resolved.skill_files:
            rel = posix_rel(skill_path, resolved.root)
            skill_id = skill_path.parent.name
            meta = parse_skill_frontmatter(skill_path.read_text(encoding="utf-8"))
            description = meta.get(
                "description",
                f"Harness Skill '{skill_id}' (see canonical SKILL.md)",
            )
            if meta.get("name") and meta["name"] != skill_id:
                warnings.append(
                    f"Skill directory '{skill_id}' frontmatter name is '{meta['name']}' "
                    "(using directory name for Claude skill folder identity)."
                )
            out_rel = f"{skills_dir}/{skill_id}/SKILL.md"
            planned.append(
                PlannedFile(
                    relative_path=out_rel,
                    content=skill_wrapper_content(skill_id, description, rel),
                    kind="skill",
                )
            )

    if resolved.tool_ids:
        if metadata.supports("tools"):
            warnings.append(
                "Tools are declared supported but this generator does not project Tools yet."
            )
        else:
            for tool_id, tool_path in zip(resolved.tool_ids, resolved.tool_files):
                tool_rel = posix_rel(tool_path, resolved.root)
                warnings.append(
                    f"Tool '{tool_id}' is selected ({tool_rel}) but Claude adapter "
                    "does not project Tools into agent config (unsupported capability)."
                )

    assert_plan_matches_capabilities(metadata, {item.kind for item in planned})
    return planned, warnings


def print_report(report, *, dry_run: bool) -> None:
    aborted = report.has_failures
    if aborted:
        mode = "Preflight failed (fail-closed)"
    elif dry_run:
        mode = "Dry-run"
    else:
        mode = "Generation"
    print(f"{mode} report")
    prospective = dry_run or aborted
    for label, items in (
        ("Would create" if prospective else "Created", report.created),
        ("Would update" if prospective else "Updated", report.updated),
        ("Would remove" if prospective else "Removed", report.removed),
        ("Unchanged", report.unchanged),
        ("Conflicts", report.conflicts),
        ("Warnings", report.warnings),
        ("Errors", report.errors),
    ):
        if not items:
            continue
        print(f"\n{label}:")
        for item in items:
            print(f"  - {item}")


def run(root: Path, *, dry_run: bool) -> int:
    try:
        metadata = load_adapter_metadata(ADAPTER_DIR / "adapter.yaml")
        resolved = resolve_harness(root)
        planned, warnings = build_plan(resolved, metadata)
    except (ResolutionError, AdapterMetadataError) as exc:
        print(f"Claude adapter failed.\n\n{exc}", file=sys.stderr)
        return 1

    manifest_rel = metadata.output_path("managed_manifest")
    manifest_file = root / manifest_rel
    previous = load_manifest(
        manifest_file,
        adapter=metadata.name,
        adapter_version=metadata.version,
    )

    report = preflight(
        root,
        planned,
        previous_files=list(previous.get("files", [])),
    )
    report.warnings.extend(warnings)

    if report.has_failures:
        print_report(report, dry_run=dry_run)
        print(
            "\nConflict policy: fail-closed. No files were modified.",
            file=sys.stderr,
        )
        return 1

    apply_preflighted_plan(
        root,
        planned,
        report,
        manifest_path=manifest_file,
        adapter=metadata.name,
        adapter_version=metadata.version,
        dry_run=dry_run,
    )
    print_report(report, dry_run=dry_run)

    if dry_run:
        print("\nDry-run complete. No files were modified.")
    else:
        print("\nClaude adapter generation complete.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Claude Code projections from .harness/harness.yaml "
            "(does not modify canonical harness resources; does not manage CLAUDE.md)."
        )
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Project root containing .harness/harness.yaml (default: repository root)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned actions without writing files",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = (args.root or REPO_ROOT_DEFAULT).resolve()
    return run(root, dry_run=bool(args.dry_run))


if __name__ == "__main__":
    sys.exit(main())
