#!/usr/bin/env python3
"""Generate Claude Code-compatible configuration from Harness configuration.

Reads .harness/harness.yaml (project intent) and writes self-contained
projections under .claude/. Resolves canonical Rules/Skills from the content
pack. Does not copy the content pack into the project. Does not manage or
overwrite project CLAUDE.md.

Treats configuration and resource files as data — never eval/exec their content.

Preferred invocation (no sys.path mutation):

    python -m adapters.claude.generate --root .

Direct script execution still works via a minimal path bootstrap for local
development without packaging.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ADAPTER_DIR = Path(__file__).resolve().parent
REPO_ROOT_DEFAULT = ADAPTER_DIR.parent.parent

# Script-mode bootstrap only. Prefer: python -m adapters.claude.generate
if __package__ is None:  # pragma: no cover - exercised via CLI subprocess
    repo_root = str(REPO_ROOT_DEFAULT)
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)

from adapters.common.apply import (  # noqa: E402
    PlannedFile,
    apply_preflighted_plan,
    load_manifest,
    preflight,
)
from adapters.common.frontmatter import (  # noqa: E402
    parse_skill_frontmatter,
    skill_body_after_frontmatter,
)
from adapters.common.metadata import (  # noqa: E402
    AdapterMetadata,
    AdapterMetadataError,
    assert_plan_matches_capabilities,
    load_adapter_metadata,
)
from adapters.common.resolve import (  # noqa: E402
    MANAGED_MARKER,
    ResolutionError,
    ResolvedHarness,
    resolve_harness,
)


def _normalize_markdown(body: str) -> str:
    normalized = body.replace("\r\n", "\n").replace("\r", "\n")
    if not normalized.endswith("\n"):
        normalized += "\n"
    return normalized


def rule_projection_content(category: str, stem: str, body: str) -> str:
    """Materialize a Claude project rule under .claude/rules/.

    Official Claude Code docs: rules are ``.md`` files under ``.claude/rules/``,
    discovered recursively. Rules without ``paths`` frontmatter load at launch.

    ``@path`` imports are documented for CLAUDE.md files, not for
    ``.claude/rules/``. This adapter embeds the canonical Rule body
    (regenerate to sync) rather than inventing an unverified import mechanism.
    """
    return (
        f"{MANAGED_MARKER}\n\n"
        f"# Harness Rule: {category}/{stem}\n\n"
        "This file is a Claude Code projection generated by the AI Engineering "
        "Harness. It is self-contained; regenerate after upgrading the Harness "
        "package to sync with canonical Rules.\n\n"
        "Do not edit this file by hand.\n\n"
        "---\n\n"
        f"{_normalize_markdown(body)}"
    )


def skill_projection_content(skill_id: str, raw_skill: str) -> tuple[str, list[str]]:
    """Materialize a self-contained Claude Skill. Returns (content, warnings)."""
    warnings: list[str] = []
    meta = parse_skill_frontmatter(raw_skill)
    description = meta.get(
        "description",
        f"Harness Skill '{skill_id}'",
    )
    if meta.get("name") and meta["name"] != skill_id:
        warnings.append(
            f"Skill directory '{skill_id}' frontmatter name is '{meta['name']}' "
            "(using directory name for Claude skill folder identity)."
        )
    safe_description = description.replace('"', "'")
    body = skill_body_after_frontmatter(raw_skill).lstrip("\n")
    content = (
        "---\n"
        f"name: {skill_id}\n"
        f'description: "{safe_description}"\n'
        "---\n\n"
        f"{MANAGED_MARKER}\n\n"
        f"{_normalize_markdown(body)}"
    )
    return content, warnings


def build_plan(
    resolved: ResolvedHarness,
    metadata: AdapterMetadata,
) -> tuple[list[PlannedFile], list[str]]:
    planned: list[PlannedFile] = []
    warnings: list[str] = []

    rules_dir = metadata.output_path("rules_dir").rstrip("/")
    skills_dir = metadata.output_path("skills_dir").rstrip("/")

    if resolved.rule_files and not metadata.supports("rules"):
        raise AdapterMetadataError(
            "Resolved Rules are selected but adapter.yaml does not support 'rules'"
        )
    if resolved.skill_files and not metadata.supports("skills"):
        raise AdapterMetadataError(
            "Resolved Skills are selected but adapter.yaml does not support 'skills'"
        )

    if metadata.supports("rules"):
        for rule_path in resolved.rule_files:
            category = rule_path.parent.name
            stem = rule_path.stem
            out_rel = f"{rules_dir}/{category}--{stem}.md"
            body = rule_path.read_text(encoding="utf-8")
            planned.append(
                PlannedFile(
                    relative_path=out_rel,
                    content=rule_projection_content(category, stem, body),
                    kind="rule",
                )
            )

    if metadata.supports("skills"):
        for skill_path in resolved.skill_files:
            skill_id = skill_path.parent.name
            raw = skill_path.read_text(encoding="utf-8")
            content, skill_warnings = skill_projection_content(skill_id, raw)
            warnings.extend(skill_warnings)
            out_rel = f"{skills_dir}/{skill_id}/SKILL.md"
            planned.append(
                PlannedFile(
                    relative_path=out_rel,
                    content=content,
                    kind="skill",
                )
            )

    if resolved.tool_ids:
        if metadata.supports("tools"):
            warnings.append(
                "Tools are declared supported but this generator does not project Tools yet."
            )
        else:
            for tool_id in resolved.tool_ids:
                warnings.append(
                    f"Tool '{tool_id}' is selected but Claude adapter "
                    "does not project Tools into agent config (unsupported capability)."
                )

    assert_plan_matches_capabilities(metadata, {item.kind for item in planned})
    return planned, warnings


def print_report(report, *, dry_run: bool) -> None:
    aborted = report.has_failures
    if aborted:
        mode = "Preflight failed (fail-closed)"
    elif dry_run:
        mode = "Dry-run"
    else:
        mode = "Generation"
    print(f"{mode} report")
    prospective = dry_run or aborted
    for label, items in (
        ("Would create" if prospective else "Created", report.created),
        ("Would update" if prospective else "Updated", report.updated),
        ("Would remove" if prospective else "Removed", report.removed),
        ("Unchanged", report.unchanged),
        ("Conflicts", report.conflicts),
        ("Warnings", report.warnings),
        ("Errors", report.errors),
    ):
        if not items:
            continue
        print(f"{label}:")
        for item in items:
            print(f"  - {item}")


def run(root: Path, *, dry_run: bool) -> int:
    try:
        metadata = load_adapter_metadata(ADAPTER_DIR / "adapter.yaml")
        resolved = resolve_harness(root)
        planned, warnings = build_plan(resolved, metadata)
    except (ResolutionError, AdapterMetadataError) as exc:
        print(f"Claude adapter failed.\n\n{exc}", file=sys.stderr)
        return 1

    manifest_rel = metadata.output_path("managed_manifest")
    manifest_file = root / manifest_rel
    previous = load_manifest(
        manifest_file,
        adapter=metadata.name,
        adapter_version=metadata.version,
    )

    report = preflight(
        root,
        planned,
        previous_files=list(previous.get("files", [])),
    )
    report.warnings.extend(warnings)

    if report.has_failures:
        print_report(report, dry_run=dry_run)
        print(
            "\nConflict policy: fail-closed. No files were modified.",
            file=sys.stderr,
        )
        return 1

    apply_preflighted_plan(
        root,
        planned,
        report,
        manifest_path=manifest_file,
        adapter=metadata.name,
        adapter_version=metadata.version,
        dry_run=dry_run,
    )
    print_report(report, dry_run=dry_run)

    if dry_run:
        print("\nDry-run complete. No files were modified.")
    else:
        print("\nClaude adapter generation complete.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate self-contained Claude Code projections from .harness/harness.yaml "
            "(does not copy the content pack into the project; does not manage CLAUDE.md)."
        )
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Project root containing .harness/harness.yaml (default: repository root)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned actions without writing files",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = (args.root or REPO_ROOT_DEFAULT).resolve()
    return run(root, dry_run=bool(args.dry_run))


if __name__ == "__main__":
    sys.exit(main())
