#!/usr/bin/env python3
"""Generate Cursor-compatible configuration from Harness configuration.

Reads .harness/harness.yaml (source of truth) and writes thin wrappers under
.cursor/. Does not modify canonical rules/, skills/, profiles/, tools/, or docs/tools/.

Treats configuration and resource files as data — never eval/exec their content.

Preferred invocation (no sys.path mutation):

    python -m adapters.cursor.generate --root .

Direct script execution still works via a minimal path bootstrap for local
development without packaging.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ADAPTER_DIR = Path(__file__).resolve().parent
REPO_ROOT_DEFAULT = ADAPTER_DIR.parent.parent

# Script-mode bootstrap only. Prefer: python -m adapters.cursor.generate
if __package__ is None:  # pragma: no cover - exercised via CLI subprocess
    repo_root = str(REPO_ROOT_DEFAULT)
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)

from adapters.common.apply import (  # noqa: E402
    PlannedFile,
    apply_preflighted_plan,
    load_manifest,
    preflight,
)
from adapters.common.frontmatter import parse_skill_frontmatter  # noqa: E402
from adapters.common.metadata import (  # noqa: E402
    AdapterMetadata,
    AdapterMetadataError,
    assert_plan_matches_capabilities,
    load_adapter_metadata,
)
from adapters.common.resolve import (  # noqa: E402
    MANAGED_MARKER,
    ResolutionError,
    ResolvedHarness,
    resolve_harness,
)

# Cursor Project Rules: alwaysApply:true injects the rule into every chat.
# Default false + description uses "Apply Intelligently" (official Cursor docs).
# See adapters/cursor/README.md — Always Apply Policy.
DEFAULT_RULE_ALWAYS_APPLY = False


def posix_rel(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def rule_wrapper_content(
    canonical_rel: str,
    category: str,
    stem: str,
    *,
    always_apply: bool = DEFAULT_RULE_ALWAYS_APPLY,
) -> str:
    description = (
        f"Harness Rule {category}/{stem}. "
        "Apply when this project's agent behavior for this category is relevant."
    )
    always_value = "true" if always_apply else "false"
    return (
        "---\n"
        f'description: "{description}"\n'
        f"alwaysApply: {always_value}\n"
        "---\n\n"
        f"{MANAGED_MARKER}\n\n"
        "Follow the canonical Harness Rule referenced below. "
        "Do not treat this wrapper as a second source of truth.\n\n"
        f"@{canonical_rel}\n"
    )


def skill_wrapper_content(skill_id: str, description: str, canonical_rel: str) -> str:
    safe_description = description.replace('"', "'")
    return (
        "---\n"
        f"name: {skill_id}\n"
        f'description: "{safe_description}"\n'
        "---\n\n"
        f"{MANAGED_MARKER}\n\n"
        f"# {skill_id}\n\n"
        "This file is a Cursor projection generated by the AI Engineering Harness.\n\n"
        "Canonical Skill (source of truth):\n\n"
        f"`{canonical_rel}`\n\n"
        "When this skill applies, read that file and follow its workflow. "
        "Do not invent steps that are not in the canonical Skill.\n"
    )


def build_plan(
    resolved: ResolvedHarness,
    metadata: AdapterMetadata,
) -> tuple[list[PlannedFile], list[str]]:
    planned: list[PlannedFile] = []
    warnings: list[str] = []

    rules_dir = metadata.output_path("rules_dir").rstrip("/")
    skills_dir = metadata.output_path("skills_dir").rstrip("/")

    if resolved.rule_files and not metadata.supports("rules"):
        raise AdapterMetadataError(
            "Resolved Rules are selected but adapter.yaml does not support 'rules'"
        )
    if resolved.skill_files and not metadata.supports("skills"):
        raise AdapterMetadataError(
            "Resolved Skills are selected but adapter.yaml does not support 'skills'"
        )

    if metadata.supports("rules"):
        for rule_path in resolved.rule_files:
            rel = posix_rel(rule_path, resolved.root)
            category = rule_path.parent.name
            stem = rule_path.stem
            out_rel = f"{rules_dir}/{category}--{stem}.mdc"
            planned.append(
                PlannedFile(
                    relative_path=out_rel,
                    content=rule_wrapper_content(rel, category, stem),
                    kind="rule",
                )
            )

    if metadata.supports("skills"):
        for skill_path in resolved.skill_files:
            rel = posix_rel(skill_path, resolved.root)
            skill_id = skill_path.parent.name
            meta = parse_skill_frontmatter(skill_path.read_text(encoding="utf-8"))
            description = meta.get(
                "description",
                f"Harness Skill '{skill_id}' (see canonical SKILL.md)",
            )
            if meta.get("name") and meta["name"] != skill_id:
                warnings.append(
                    f"Skill directory '{skill_id}' frontmatter name is '{meta['name']}' "
                    "(using directory name for Cursor folder identity)."
                )
            out_rel = f"{skills_dir}/{skill_id}/SKILL.md"
            planned.append(
                PlannedFile(
                    relative_path=out_rel,
                    content=skill_wrapper_content(skill_id, description, rel),
                    kind="skill",
                )
            )

    if resolved.tool_ids:
        if metadata.supports("tools"):
            warnings.append(
                "Tools are declared supported but this generator does not project Tools yet."
            )
        else:
            for tool_id, tool_path in zip(resolved.tool_ids, resolved.tool_files):
                tool_rel = posix_rel(tool_path, resolved.root)
                warnings.append(
                    f"Tool '{tool_id}' is selected ({tool_rel}) but Cursor adapter "
                    "does not project Tools into agent config (unsupported capability)."
                )

    assert_plan_matches_capabilities(metadata, {item.kind for item in planned})
    return planned, warnings


def print_report(report, *, dry_run: bool) -> None:
    aborted = report.has_failures
    if aborted:
        mode = "Preflight failed (fail-closed)"
    elif dry_run:
        mode = "Dry-run"
    else:
        mode = "Generation"
    print(f"{mode} report")
    prospective = dry_run or aborted
    for label, items in (
        ("Would create" if prospective else "Created", report.created),
        ("Would update" if prospective else "Updated", report.updated),
        ("Would remove" if prospective else "Removed", report.removed),
        ("Unchanged", report.unchanged),
        ("Conflicts", report.conflicts),
        ("Warnings", report.warnings),
        ("Errors", report.errors),
    ):
        if not items:
            continue
        print(f"\n{label}:")
        for item in items:
            print(f"  - {item}")


def run(root: Path, *, dry_run: bool) -> int:
    try:
        metadata = load_adapter_metadata(ADAPTER_DIR / "adapter.yaml")
        resolved = resolve_harness(root)
        planned, warnings = build_plan(resolved, metadata)
    except (ResolutionError, AdapterMetadataError) as exc:
        print(f"Cursor adapter failed.\n\n{exc}", file=sys.stderr)
        return 1

    manifest_rel = metadata.output_path("managed_manifest")
    manifest_file = root / manifest_rel
    previous = load_manifest(
        manifest_file,
        adapter=metadata.name,
        adapter_version=metadata.version,
    )

    report = preflight(
        root,
        planned,
        previous_files=list(previous.get("files", [])),
    )
    report.warnings.extend(warnings)

    if report.has_failures:
        print_report(report, dry_run=dry_run)
        print(
            "\nConflict policy: fail-closed. No files were modified.",
            file=sys.stderr,
        )
        return 1

    apply_preflighted_plan(
        root,
        planned,
        report,
        manifest_path=manifest_file,
        adapter=metadata.name,
        adapter_version=metadata.version,
        dry_run=dry_run,
    )
    print_report(report, dry_run=dry_run)

    if dry_run:
        print("\nDry-run complete. No files were modified.")
    else:
        print("\nCursor adapter generation complete.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Cursor wrappers from .harness/harness.yaml "
            "(does not modify canonical harness resources)."
        )
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Project root containing .harness/harness.yaml (default: repository root)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned actions without writing files",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = (args.root or REPO_ROOT_DEFAULT).resolve()
    return run(root, dry_run=bool(args.dry_run))


if __name__ == "__main__":
    sys.exit(main())
